name: 'GitHub Actions environments exporter'
description: 'Exporting ACTIONS_RUNTIME_TOKEN and ACTIONS_CACHE_URL to enable the Docker layer caching on GitHub Actions.'
author: 'peaceiris'
branding:
  icon: 'upload'
  color: 'gray-dark'
runs:
  using: 'docker'
  image: 'Dockerfile'
outputs:
  ACTIONS_RUNTIME_TOKEN:
    description: 'ACTIONS_RUNTIME_TOKEN env'
  ACTIONS_CACHE_URL:
    description: 'ACTIONS_CACHE_URL env'
  ACTIONS_RESULTS_URL:
    description: 'ACTIONS_RESULTS_URL env'
