name: CI

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/ci.yaml"
      - "Makefile"
      - "Dockerfile"
      - ".dockerignore"
      - "action.yml"
      - "entrypoint.sh"
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/ci.yaml"
      - "Makefile"
      - "Dockerfile"
      - ".dockerignore"
      - "action.yml"
      - "entrypoint.sh"

jobs:
  main:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    permissions: {}
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - uses: ./
        id: envs

      - run: echo "dump outputs"
        env:
          ACTIONS_RUNTIME_TOKEN: ${{ steps.envs.outputs.ACTIONS_RUNTIME_TOKEN }}
          ACTIONS_CACHE_URL: ${{ steps.envs.outputs.ACTIONS_CACHE_URL }}
